import { INodeProperties } from 'n8n-workflow';

const properties: INodeProperties[] = [
  {
    "displayName": 'Resource',
    "name": 'resource',
    "type": 'options',
    "default": '',
    "description": 'Select the resource to work with',
    "options": [
      {
        "name": 'config',
        "value": 'config',
        "description": 'Manage your Advanced Personalization configuration'
      },
      {
        "name": 'users',
        "value": 'users',
        "description": 'Manage user profiles generated by Advanced Personalization'
      }
    ]
  },
  {
    "displayName": 'Operation',
    "name": 'operation',
    "type": 'options',
    "default": '',
    "description": 'Select the operation to work with',
    "options": [
      {
        "name": 'Retrieve the configuration',
        "value": 'getConfig',
        "action": 'Retrieve the configuration',
        "description": 'Retrieves a list of configuration objects for each index.',
        "routing": {
          "request": {
            "method": 'GET',
            "url": '=/2/config'
          }
        }
      },
      {
        "name": 'Update the configuration',
        "value": 'putConfig',
        "action": 'Update the configuration',
        "description": 'Updates the configuration.',
        "routing": {
          "request": {
            "method": 'PUT',
            "url": '=/2/config'
          }
        }
      }
    ],
    "displayOptions": {
      "show": {
        "resource": [
          'config'
        ]
      }
    }
  },
  {
    "displayName": 'Operation',
    "name": 'operation',
    "type": 'options',
    "default": '',
    "description": 'Select the operation to work with',
    "options": [
      {
        "name": 'Get a list of user profiles',
        "value": 'getUsers',
        "action": 'Get a list of user profiles',
        "description": 'Retrieves a list of user profiles in [lexicographical order](https://www.educative.io/answers/what-is-a-lexicographic-order).',
        "routing": {
          "request": {
            "method": 'GET',
            "url": '=/2/users'
          }
        }
      },
      {
        "name": 'Get a user profile',
        "value": 'getUser',
        "action": 'Get a user profile',
        "description": 'Retrieves a user profile.',
        "routing": {
          "request": {
            "method": 'GET',
            "url": '=/2/users/{{ $parameter.userID_string }}'
          }
        }
      },
      {
        "name": 'Delete a user profile',
        "value": 'deleteUser',
        "action": 'Delete a user profile',
        "description": 'Deletes a user profile.',
        "routing": {
          "request": {
            "method": 'DELETE',
            "url": '=/2/users/{{ $parameter.userID_string }}'
          }
        }
      },
      {
        "name": 'Retrieve the real-time user\'s personalization profile',
        "value": 'getRealtimeUser',
        "action": 'Retrieve the real-time user\'s personalization profile',
        "description": 'Retrieves the real-time user\'s personalization profiles containing search filters.',
        "routing": {
          "request": {
            "method": 'GET',
            "url": '=/2/realtime/users/{{ $parameter.userToken_string }}'
          }
        }
      },
      {
        "name": 'Compute the real-time user\'s personalization profile',
        "value": 'computeRealtimeUser',
        "action": 'Compute the real-time user\'s personalization profile',
        "description": 'Sends a request to compute the real-time user\'s personalization profile.',
        "routing": {
          "request": {
            "method": 'POST',
            "url": '=/2/realtime/users/{{ $parameter.userToken_string }}/compute'
          }
        }
      }
    ],
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ]
      }
    }
  },
  {
    "displayName": 'Configuration Parameters',
    "name": 'configuration_parameters_object',
    "type": 'multiOptions',
    "description": undefined,
    "required": true,
    "default": [],
    "options": [
      {
        "name": 'Indices',
        "value": 'indices_json'
      },
      {
        "name": 'Personalization Re Ranking',
        "value": 'personalizationReRanking_options'
      },
      {
        "name": 'Profile Type',
        "value": 'profileType_options'
      },
      {
        "name": 'Features',
        "value": 'features_object'
      }
    ],
    "displayOptions": {
      "show": {
        "resource": [
          'config'
        ],
        "operation": [
          'putConfig'
        ]
      }
    }
  },
  {
    "type": 'json',
    "displayName": 'Indices',
    "name": 'indices_json',
    "default": '[]',
    "description": undefined,
    "required": true,
    "routing": {
      "send": {
        "type": 'body',
        "value": '={{ JSON.parse($value) }}',
        "property": 'indices'
      }
    },
    "displayOptions": {
      "show": {
        "configuration_parameters_object": [
          'indices_json'
        ],
        "resource": [
          'config'
        ],
        "operation": [
          'putConfig'
        ]
      }
    }
  },
  {
    "type": 'options',
    "default": '',
    "description": 'The impact that personalization has on the re-ranking of search results.',
    "options": [
      {
        "name": 'none',
        "value": 'none'
      },
      {
        "name": 'low',
        "value": 'low'
      },
      {
        "name": 'medium',
        "value": 'medium'
      },
      {
        "name": 'high',
        "value": 'high'
      },
      {
        "name": 'maximum',
        "value": 'maximum'
      }
    ],
    "routing": {
      "send": {
        "type": 'body',
        "value": '={{ $value }}',
        "property": 'personalizationReRanking'
      }
    },
    "displayName": 'Personalization Re Ranking',
    "name": 'personalizationReRanking_options',
    "displayOptions": {
      "show": {
        "configuration_parameters_object": [
          'personalizationReRanking_options'
        ],
        "resource": [
          'config'
        ],
        "operation": [
          'putConfig'
        ]
      }
    },
    "required": true
  },
  {
    "type": 'options',
    "default": '',
    "description": 'The type of user profiles to generate.\n\nBasic profiles are based on past behaviors, ensuring search results align with previous interests.\n',
    "options": [
      {
        "name": 'basic',
        "value": 'basic'
      }
    ],
    "routing": {
      "send": {
        "type": 'body',
        "value": '={{ $value }}',
        "property": 'profileType'
      }
    },
    "displayName": 'Profile Type',
    "name": 'profileType_options',
    "displayOptions": {
      "show": {
        "configuration_parameters_object": [
          'profileType_options'
        ],
        "resource": [
          'config'
        ],
        "operation": [
          'putConfig'
        ]
      }
    },
    "required": true
  },
  {
    "type": 'json',
    "description": undefined,
    "required": true,
    "default": '{}',
    "routing": {
      "send": {
        "type": 'body',
        "property": 'features',
        "value": '={{ JSON.parse($value) }}'
      }
    },
    "displayName": 'Features',
    "name": 'features_object',
    "displayOptions": {
      "show": {
        "configuration_parameters_object": [
          'features_object'
        ],
        "resource": [
          'config'
        ],
        "operation": [
          'putConfig'
        ]
      }
    }
  },
  {
    "type": 'string',
    "placeholder": '2024-06-27T08:27:26Z',
    "default": '',
    "routing": {
      "request": {
        "qs": {
          "startDate": '={{ $value }}'
        }
      }
    },
    "displayName": 'Start Date',
    "name": 'startDate_string',
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'getUsers'
        ]
      }
    }
  },
  {
    "type": 'string',
    "placeholder": '2024-06-28T08:27:26Z',
    "default": '',
    "routing": {
      "request": {
        "qs": {
          "endDate": '={{ $value }}'
        }
      }
    },
    "displayName": 'End Date',
    "name": 'endDate_string',
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'getUsers'
        ]
      }
    }
  },
  {
    "type": 'json',
    "displayName": 'Indices',
    "name": 'indices_json',
    "default": '[]',
    "description": undefined,
    "required": false,
    "routing": {
      "request": {
        "qs": {
          "indices": '={{ JSON.parse($value) }}'
        }
      }
    },
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'getUsers'
        ]
      }
    }
  },
  {
    "type": 'json',
    "displayName": 'Affinity',
    "name": 'affinity_json',
    "default": '[]',
    "description": undefined,
    "required": false,
    "routing": {
      "request": {
        "qs": {
          "affinity": '={{ JSON.parse($value) }}'
        }
      }
    },
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'getUsers'
        ]
      }
    }
  },
  {
    "type": 'number',
    "default": 10,
    "typeOptions": {
      "minValue": 1,
      "maxValue": 1000
    },
    "routing": {
      "request": {
        "qs": {
          "limit": '={{ $value }}'
        }
      }
    },
    "displayName": 'Limit',
    "name": 'limit_number',
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'getUsers'
        ]
      }
    }
  },
  {
    "type": 'string',
    "default": '',
    "routing": {
      "request": {
        "qs": {
          "nextPageToken": '={{ $value }}'
        }
      }
    },
    "displayName": 'Next Page Token',
    "name": 'nextPageToken_string',
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'getUsers'
        ]
      }
    }
  },
  {
    "type": 'string',
    "default": '',
    "routing": {
      "request": {
        "qs": {
          "previousPageToken": '={{ $value }}'
        }
      }
    },
    "displayName": 'Previous Page Token',
    "name": 'previousPageToken_string',
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'getUsers'
        ]
      }
    }
  },
  {
    "type": 'string',
    "default": '',
    "displayName": 'User ID',
    "name": 'userID_string',
    "required": true,
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'getUser'
        ]
      }
    }
  },
  {
    "type": 'string',
    "default": '',
    "displayName": 'User ID',
    "name": 'userID_string',
    "required": true,
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'deleteUser'
        ]
      }
    }
  },
  {
    "type": 'string',
    "placeholder": 'test-user-123',
    "default": '',
    "description": 'Unique pseudonymous or anonymous user identifier.\n\nThis helps with analytics and click and conversion events.\nFor more information, see [user token](https://www.algolia.com/doc/guides/sending-events/concepts/usertoken).\n',
    "displayName": 'User Token',
    "name": 'userToken_string',
    "required": true,
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'getRealtimeUser'
        ]
      }
    }
  },
  {
    "type": 'string',
    "placeholder": 'test-user-123',
    "default": '',
    "description": 'Unique pseudonymous or anonymous user identifier.\n\nThis helps with analytics and click and conversion events.\nFor more information, see [user token](https://www.algolia.com/doc/guides/sending-events/concepts/usertoken).\n',
    "displayName": 'User Token',
    "name": 'userToken_string',
    "required": true,
    "displayOptions": {
      "show": {
        "resource": [
          'users'
        ],
        "operation": [
          'computeRealtimeUser'
        ]
      }
    }
  }
];

export default properties;
