// Auto-generated file - do not edit manually
// Generated by scripts/generate-specs-index.ts

import abtesting from './abtesting';
import abtestingv3 from './abtesting-v3';
import advancedpersonalization from './advanced-personalization';
import analytics from './analytics';
import composition from './composition';
import crawler from './crawler';
import ingestion from './ingestion';
import insights from './insights';
import monitoring from './monitoring';
import personalization from './personalization';
import querysuggestions from './query-suggestions';
import recommend from './recommend';
import search from './search';

export default {
  abtesting,
  abtestingv3,
  advancedpersonalization,
  analytics,
  composition,
  crawler,
  ingestion,
  insights,
  monitoring,
  personalization,
  querysuggestions,
  recommend,
  search,
};
