import * as fs from 'fs';
import * as path from 'path';

/**
 * Script to automatically generate index.ts file with exports for all TypeScript files
 * in the specs directory, excluding the index.ts file itself.
 */

const SPECS_DIR = path.join(__dirname, '..', 'nodes', 'Algolia', 'specs');
const INDEX_FILE = path.join(SPECS_DIR, 'index.ts');

function generateSpecsIndex(): void {
	try {
		// Read all files in the specs directory
		const files = fs.readdirSync(SPECS_DIR);

		// Filter for TypeScript files, excluding index.ts
		const tsFiles = files
			.filter((file) => file.endsWith('.ts') && file !== 'index.ts')
			.map((file) => file.replace('.ts', ''))
			.sort();

		if (tsFiles.length === 0) {
			console.log('No TypeScript files found in specs directory');
			return;
		}

		// Generate the index.ts content
		const header =
			'// Auto-generated file - do not edit manually\n// Generated by scripts/generate-specs-index.ts\n\n';
		const exports = tsFiles
			.map((file) => `import ${file.replace('-', '')} from './${file}';`)
			.join('\n');
		const defaultExport =
			'\n\nexport default { ' + tsFiles.map((file) => file.replace('-', '')).join(', ') + ' };';
		const content = header + exports + defaultExport + '\n';

		fs.writeFileSync(INDEX_FILE, content, 'utf8');
	} catch (error) {
		console.error('Error generating specs index:', error);
		process.exit(1);
	}
}

if (require.main === module) {
	generateSpecsIndex();
}
