name: Format Changelog

on:
  pull_request:
    paths:
      - 'CHANGELOG.md'

jobs:
  changelog-format:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Format code
        run: npx prettier --write .

      - name: Commit and push
        uses: ./.github/actions/commit-and-push
        with:
          commit-message: 'chore(changelog): format'
          github-token: ${{ secrets.ALGOLIA_BOT_TOKEN }}
